# Generated by Django 4.2.5 on 2023-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nakamoto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="otp_key",
            field=models.CharField(default="default", max_length=32),
            preserve_default=False,
        ),
    ]
